"""MemoryStore protocol — the storage abstraction."""

from __future__ import annotations

from typing import Protocol

from cascade_api.memory.models import MemoryLink, MemoryRecord, SearchResult


class MemoryStore(Protocol):
    async def get_core(self, tenant_id: str) -> tuple[str, int]: ...
    async def upsert_core(self, tenant_id: str, content: str, expected_version: int) -> int: ...

    async def save(self, tenant_id: str, memory: MemoryRecord) -> str: ...
    async def save_batch(self, tenant_id: str, memories: list[MemoryRecord]) -> list[str]: ...
    async def get(self, tenant_id: str, memory_id: str) -> MemoryRecord: ...
    async def list(
        self, tenant_id: str, status: str = "active", limit: int = 50
    ) -> list[MemoryRecord]: ...
    async def update(
        self,
        tenant_id: str,
        memory_id: str,
        content: str | None = None,
        status: str | None = None,
        embedding: list[float] | None = None,
        superseded_by: str | None = None,
    ) -> None: ...
    async def search(
        self,
        tenant_id: str,
        embedding: list[float],
        count: int = 5,
        threshold: float = 0.5,
    ) -> list[SearchResult]: ...

    async def delete(self, tenant_id: str, memory_id: str) -> None: ...
    async def delete_all(self, tenant_id: str) -> int: ...

    async def add_link(
        self, tenant_id: str, source_id: str, target_id: str, link_type: str
    ) -> None: ...
    async def get_links(self, tenant_id: str, memory_id: str) -> list[MemoryLink]: ...

    async def update_decay_scores(self, decay_rate: float = 0.95) -> int: ...
    async def touch_accessed(self, tenant_id: str, memory_ids: list[str]) -> None: ...

    async def initialize(self, embedding_dimensions: int) -> None: ...
